apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: orderResiliency
spec:
  policies:
    retries:
      pubSubRetry:
        policy: constant
        duration: 5s
        maxRetries: 5
  targets:
    components:
      pubsub:
        inbound:
          retry: pubSubRetry